package ledger

import (
	"bytes"
	"database/sql"
	"strings"
	"testing"

	"localledger/internal/models"

	"golang.org/x/text/encoding/charmap"
)

func TestGenerateSIE4_ValidStructure(t *testing.T) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatalf("Failed to open memory DB: %v", err)
	}

	// Kör initierings-schema (inkluderar nu BAS K1 och v11 konton)
	if err := runMigrations(db); err != nil {
		t.Fatalf("Failed to initialize schema: %v", err)
	}
	defer db.Close()

	l := &Ledger{db: db}

	// 1. Skapa Räkenskapsår (olåst initialt så vi kan lägga till verifikationer)
	_, err = l.db.Exec(`
		DELETE FROM fiscal_years;
		INSERT INTO fiscal_years (id, start_date, end_date) VALUES (1, '2026-01-01', '2026-12-31')
	`)
	if err != nil {
		t.Fatalf("Failed to create fiscal year: %v", err)
	}

	// 2. Skapa lite test-verifikationer
	tx, _ := l.db.Begin()
	_, _, err = l.postVerificationTx(tx, "Tester", models.VerificationRequest{
		Date: "2026-06-01",
		Text: "Försäljning",
		Type: "NORMAL",
		Rows: []models.RowRequest{
			{Account: "1930", Debet: 10000, Kredit: 0},
			{Account: "3001", Debet: 0, Kredit: 10000},
		},
	})
	if err != nil {
		tx.Rollback()
		t.Fatalf("Failed to post verification: %v", err)
	}
	tx.Commit()

	// Lås räkenskapsåret efter att verifikationerna postats för att bevisa #FLAGGA 0 export
	_, err = l.db.Exec("UPDATE fiscal_years SET locked_at = '2026-12-31 23:59:59' WHERE id = 1")
	if err != nil {
		t.Fatalf("Failed to lock fiscal year: %v", err)
	}

	// 3. Generera SIE-4
	sieBytes, err := l.GenerateSIE4(1)
	if err != nil {
		t.Fatalf("Failed to generate SIE4: %v", err)
	}

	if len(sieBytes) == 0 {
		t.Fatal("SIE4 generated bytes is empty")
	}

	// 4. Konvertera PC8 (CP437) tillbaka till UTF-8 för att testa innehållet i strängar
	decoder := charmap.CodePage437.NewDecoder()
	utf8Bytes, err := decoder.Bytes(sieBytes)
	if err != nil {
		t.Fatalf("Failed to decode PC8 to UTF-8: %v", err)
	}
	sieStr := string(utf8Bytes)

	// 5. Assertions för obligatoriska SIE-taggar
	expectedTags := []string{
		"#FLAGGA 0",
		"#FORMAT PC8",
		"#SIETYP 4",
		"#PROGRAM \"LocalLedger\"",
		"#KPTYP BAS2024",
		"#RAR 0 20260101 20261231",
	}

	for _, tag := range expectedTags {
		if !strings.Contains(sieStr, tag) {
			t.Errorf("Missing expected header tag: %s", tag)
		}
	}

	// Kolla om konton finns (1930, 3001)
	if !strings.Contains(sieStr, "#KONTO 1930") {
		t.Errorf("Missing account 1930 in SIE-4")
	}
	if !strings.Contains(sieStr, "#KONTO 3001") {
		t.Errorf("Missing account 3001 in SIE-4")
	}

	// Kolla om verifikationen exporterades korrekt (#VER och #TRANS)
	if !strings.Contains(sieStr, "#VER A 1 20260601 \"Försäljning\"") {
		t.Errorf("Missing #VER block for verification 1")
	}

	// Kontrollera raderna: debet är positivt (+100.00), kredit är negativt (-100.00)
	if !strings.Contains(sieStr, "#TRANS 1930 {} 100.00") {
		t.Errorf("Missing debet #TRANS for 1930")
	}
	if !strings.Contains(sieStr, "#TRANS 3001 {} -100.00") {
		t.Errorf("Missing kredit #TRANS for 3001")
	}

	// Kontrollera Resultat (#RES) och Utgående Balans (#UB)
	// 1930 ska ha #UB, 3001 ska ha #RES
	if !strings.Contains(sieStr, "#UB 0 1930 100.00") {
		t.Errorf("Missing #UB for account 1930")
	}
	if !strings.Contains(sieStr, "#RES 0 3001 -100.00") {
		t.Errorf("Missing #RES for account 3001")
	}

	// Kolla att radslut är korrekt CRLF enligt SIE-standarden
	if !bytes.Contains(sieBytes, []byte("\r\n")) {
		t.Errorf("SIE-4 filen saknar Windows CRLF line endings, vilket är ett krav.")
	}
}
